server:
  port: 8080

spring:
  application:
    name: order-event-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      group-id: inventory-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.vipinrajak.orderservice.model"
        spring.json.value.default.type: com.vipinrajak.orderservice.model.OrderCreatedEvent
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info
